# Generated by Django 4.2.7 on 2023-12-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_mall_city_mall_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mall',
            name='city',
            field=models.ManyToManyField(to='main.city'),
        ),
    ]
